### ISSUE TITLE
Make language select instant

### ISSUE THREAD

**Issue by ivanlori** [ivanlori/CV-builder#3]
The language select, in the top side of the sidebar, has to change all the platform's labels instantly. Now you can see the change only when go to another section.

**Comment by GentileFulvio** [comment]
Cloned the repository but wasn't able to compile it. 
![image](https://user-images.githubusercontent.com/17174077/69576155-0af82100-0fcc-11ea-8d04-f726289ea6d9.png)

**Comment by GentileFulvio** [comment]
Retried with `yarn` instead of `npm` but it's even worse. Any idea ?
![image](https://user-images.githubusercontent.com/17174077/69576452-9b366600-0fcc-11ea-9617-e3b9ce0a66b3.png)

**Comment by ivanlori** [comment]
Hi @GentileFulvio , yes, this issue is boring me continuously and for now I don't understand why. But if you follow the instructions it'll works. So with yarn, start deleting "node_modules" and then yarn.lock and finally run "yarn install".

**Comment by ivanlori** [comment]
@GentileFulvio I think I resolved the issue, I've just updated the react-script version to the newest. You can pull form master
